# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgis
  encoding: unicode
  username: eme
  host: localhost
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: overture_demo_development

test:
  <<: *default
  database: overture_demo_test

production:
  <<: *default
  database: overture_demo_production
  password: <%= ENV["OVERTURE_DEMO_DATABASE_PASSWORD"] %>
